### PR TITLE
less than when it should be greater than

### PR DESCRIPTION
**Pull request by shua**
Currently:
```
Compute bge_nat 1 2.
(* = true : bool *)
```

To verify this, you want some trivial proof added? eg
```
Example test_bge_nat : (bge_nat 1 2) = false.
Proof. simpl. reflexivity. Qed.
```

### CODE REVIEW

**Comment by shua** [comment]
cc @benl23x5 this ^ is still relevant (thanks for the code and site by the way)

**Comment by shua** [comment]
@benl23x5 
image

**Comment by tmcdonell** [comment]
Hi @shua, sorry for the radio silence. I don't think Ben pays attention to GitHub notifications, but (as it turns out) I can merge this for you.

**Comment by tmcdonell** [comment]
Thanks!

**Pull request merged**
